# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Some-App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fc63816920114d8fb106f694b58be372 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2dccc8e698f146949bb843abf6341664 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_fc63816920114d8fb106f694b58be372 }}/yauhenii/template:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Some-App'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a6f9a6ba8b1446ef9b76a5e63f705bc2 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_fc63816920114d8fb106f694b58be372 }}/yauhenii/template:${{ github.sha }}'